name: .NET Build

# Trigger the workflow on push or pull request
on:
  push:
    branches: ["master"]
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.axaml"
      - "**.cpp"
      - "**.h"
      - "**.hpp"
      - ".github/workflows/dotnet.yaml"
      - "CMakeLists.txt"
      - "**.cmake"
      - "OpenSteamworks.Native.nativeproj"
      - "nuget.config"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Download repo and submodules
      run: | 
        git submodule update --init --recursive
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install build dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib 

    # This is terrible, but until GH updates their runners to ubuntu 23.04 this is the terribleness we need to do
    # Or we could self-host, but I don't have dedicated hardware for it (read: my PC is not available 24/7)
    - name: Install unsupported build dependencies from lunar repoes
      run: |
        sudo sh -c "echo 'deb http://azure.archive.ubuntu.com/ubuntu lunar main restricted universe multiverse' >> /etc/apt/sources.list.d/lunar-packages.list"
        echo "content of /etc/apt/sources.list.d/lunar-packages.list"
        cat /etc/apt/sources.list.d/lunar-packages.list
        echo "end of contents"
        sudo apt-get update
        sudo apt-get install -t "lunar*" -y gcc-mingw-w64-i686-posix g++-mingw-w64-i686-posix g++-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix

    - name: Build and pack release
      run: dotnet pack -c Release

    - name: Set version env
      run: echo "BuiltVersion=$(dotnet msbuild -getproperty:Version)" >> $GITHUB_ENV

    - name: Upload to NuGet.org
      run: dotnet nuget push ${{ github.workspace }}/artifacts/package/release/OpenSteamworks.Native.${{ env.BuiltVersion }}.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json

    
